site_name: Matthew Chandler
site_url: https://machandler.com
site_author: Matthew Chandler

docs_dir: docs

repo_url: https://github.com/matthew-chandler/website
edit_uri: edit/main/docs

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye
  features:
    - content.action.view
    - content.action.edit
  custom_dir: overrides

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
      type: date