site_name: Matthew Chandler
site_url: https://www.machandler.com
site_author: Matthew Chandler

docs_dir: docs

repo_url: https://github.com/matthew-chandler/website
edit_uri: edit/main/docs

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye
  features:
    - content.action.view
    - content.action.edit
    - navigation.footer
    - navigation.indexes
  custom_dir: overrides

extra:
  generator: true
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/matthew-chandler
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/chandler-matthew/
    - icon: fontawesome/brands/discord
      link: https://discord.com/users/295627107113893898
    - icon: fontawesome/brands/square-letterboxd
      link: https://letterboxd.com/matthewchandler/
    - icon: fontawesome/brands/goodreads
      link: https://www.goodreads.com/user/show/184444701-matthew-chandler
    - icon: fontawesome/brands/steam
      link: https://steamcommunity.com/id/mipsytheblue/)

plugins:
  - git-revision-date-localized:
      enable_creation_date: true
      type: date
  - social
  - redirects:
      redirect_maps:
        '31-days/Day1.md' : "https://sun.machandler.com"
        '31-days/Day2.md' : "https://uuixd.machandler.com"
        '31-days/Day3.md' : "https://cps.machandler.com"
        '31-days/Day4.md' : "https://fireworks.machandler.com"
        '31-days/Day5.md' : "https://population.machandler.com"
        '31-days/Day6.md' : "https://league.machandler.com"

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
